version: '3.8'

services:
  postgres-clientes:
    image: postgres:15-alpine
    container_name: postgres-clientes
    environment:
      POSTGRES_DB: db_clientes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - pgdata-clientes:/var/lib/postgresql/data
      - ./ms-clientes/BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql
    networks:
      - banco-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres-cuentas:
    image: postgres:15-alpine
    container_name: postgres-cuentas
    environment:
      POSTGRES_DB: db_cuentas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata-cuentas:/var/lib/postgresql/data
      - ./ms-cuentas/BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql
    networks:
      - banco-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # Rabbit
      - "15672:15672"  # Management
    networks:
      - banco-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  ms-clientes:
    build:
      context: ./ms-clientes
      dockerfile: Dockerfile
    container_name: ms-clientes
    ports:
      - "9081:8081"
      - "5005:5005"
    environment:
      DB_HOST: postgres-clientes
      DB_PORT: 5432
      DB_NAME: db_clientes
      DB_USER: postgres
      DB_PASS: postgres
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASS: guest
    depends_on:
      postgres-clientes:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - banco-net
    restart: on-failure

  ms-cuentas:
    build:
      context: ./ms-cuentas
      dockerfile: Dockerfile
    container_name: ms-cuentas
    ports:
      - "9082:8082"
      - "5006:5006"  # Debug remoto
    environment:
      DB_HOST: postgres-cuentas
      DB_PORT: 5432
      DB_NAME: db_cuentas
      DB_USER: postgres
      DB_PASS: postgres
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASS: guest
    depends_on:
      postgres-cuentas:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - banco-net
    restart: on-failure
volumes:
  pgdata-clientes:
  pgdata-cuentas:
networks:
  banco-net:
    driver: bridge
